# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-02 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='database',
            field=models.CharField(choices=[(b'default', b'default'), (b'db1', b'db1'), (b'db2', b'db2')], default=b'default', max_length=255),
        ),
    ]
